JasonEtco/create-an-issue

- entrypoint.js
- index.js
- package-lock.json
- package.json
- tests/index.test.js
Tiny improvement, this PR makes use of `Toolkit.arguments` instead of manually getting the template name off of `process.argv`.
> Use actions-toolkit for arg parsing

- Dockerfile
- entrypoint.js
Pointed out in #3, this PR fixes a bug where in the `entrypoint.js` file (a file that isn't covered by the tests), we're importing Toolkit as a default export, but it should be a named export:
```diff
- const Toolkit = require('actions-toolkit')
+ const { Toolkit } = require('actions-toolkit')
```
I'll take a look at minimizing the work in `entrypoint.js` to avoid things like this in the future.
Closes #3
> Make it not broken

- index.js
- package-lock.json
- package.json
- tests/__snapshots__/index.test.js.snap
- tests/fixtures/.github/kitchen-sink.md
- tests/fixtures/.github/variables.md
- tests/index.test.js
- tests/setup.js
Turns out that not every event comes with a repository object on the payload, but we can rely on the `GITHUB_REPOSITORY` environment variable instead.
> Use GITHUB_REPOSITORY instead of context.repo()

- Dockerfile
- entrypoint.js
- index.js
- package-lock.json
- package.json
- tests/__snapshots__/index.test.js.snap
- tests/fixtures/event.json
- tests/index.test.js
This PR updates `actions-toolkit` to `2.0.0`. There are a couple of breaking changes, outlined [in this release](https://github.com/JasonEtco/actions-toolkit/releases/tag/v2.0.0-beta.0). Right now I'm using the `@beta` tag until we're all set with the 2.0.0 release - and I'm using this as a way to validate the upgrade steps and make sure that its all good.
Follow along: https://github.com/JasonEtco/actions-toolkit/pull/62.
> actions-toolkit@2.0.0

- index.js
- package-lock.json
- package.json
- tests/__snapshots__/index.test.js.snap
- tests/index.test.js
- tests/setup.js
I want to make use of some of the internal validation functionality of `@octokit/rest` methods, which means that I can't continue to mock those methods in tests without mocking the validation as well. So, this PR refactors the testing setup to use `nock`.
I've also swapped some log levels around to be a little more clear about their reason for existing.
> Rewrite tests in nock

- index.js
- tests/__snapshots__/index.test.js.snap
- tests/index.test.js
When creating the issue fails, an unhelpful error message is logged. This can be for a lot of reasons, including malformed issue front-matter or trying to assign a user that doesn't exist. This PR logs a more helpful error message, as well as the error:
cc @janester
> Throw helpful error when issue creation fails

- README.md
- action.yml
- index.js
- package-lock.json
- package.json
- tests/index.test.js
In Actions v2, actions can have "inputs" - these are defined:
```yaml
uses: some/action
with:
key: value
```
The official [actions/toolkit](https://github.com/actions/toolkit) has a method to get them: `core.getInput()`. Under the hood, those values are set as `process.env[`INPUT_${name.toUpperCase()}`] (hence the test changes).
This is a breaking change! It'll be released as v2.0.0 of this action.
> Use inputs instead of args for custom filename

- README.md
I found that creating an issue with a custom template failed because the file couldn't be found locally. Adding the checkout Action solved the problem for me, so I figured I'd submit a change for the docs.
I'm not sure if this is because I was working in a private repo or if it needs to be used in all cases 🤷‍♂
> Add checkout Action so the template can be found

- README.md
- action.yml
- index.js
- tests/__snapshots__/index.test.js.snap
- tests/index.test.js
Adds the ability to set the assignee by input if you need to use Action logic to determine to whom the issue should be assigned.
> Add assignee input

- README.md
- action.yml
- index.js
- tests/index.test.js
* Adds a `url` output that contains the `html_url` for the issue that was created.
* Adds a `number` output that contains the number of the issue that was created.
I couldn't figure out how to hook this into the test framework since it seems all the mocking and such goes through `toolkit`, not `core`, so I didn't add any test code for it. If you've got some ideas, let me know and I'd be happy to add it.
> Add number and url outputs

- index.js
- package-lock.json
- package.json
- tests/__snapshots__/index.test.js.snap
- tests/index.test.js
This PR upgrades dependencies, including `actions-toolkit` to `3.0.0`. I've then used `tools.inputs` over `core.getInput()`s, and added a `core.setFailed` for better error reporting.
> Upgrade dependencies and use core things

- index.js
- tests/index.test.js
Fixes https://github.com/JasonEtco/create-an-issue/issues/46
Made the requested change. I don't see any tests that explicitly cover this, but maybe I missed them in my rush 😬
> Coerce the number value into a string

- README.md
- action.yml
- index.js
- tests/__snapshots__/index.test.js.snap
- tests/index.test.js
Hey @JasonEtco, I tried to implement #63 , but I'm a bit out of my depth here as I'm not familiar with developing actions. How can I test these changes without publishing my fork on the marketplace?
> Add updating existing open issue with the same title if it exists

- README.md
I just came back to enable this in our repo, and spotted that the wording in the readme was slightly off.
> Fix readme wording for option to update existing issue

- README.md
- src/action.ts
- tests/__snapshots__/index.test.ts.snap
- tests/fixtures/.github/context-repo-template.md
- tests/index.test.ts
Adding the `repo: tools.context.repo,` to the `templateVariables` allows us to use `{{ repo.owner }}` and `{{ repo.repo }}` in the issue template mark down.
One example useful test-case with this is for constructing links to the `gh-pages` static web pages without having to hardcode these parameters or manipulate the `GITHUB_REPOSITORY` variable:
e.g. `https://{{ repo.owner }}.github.io/{{ repo.repo }}/path/to/my/pageindex.html`
Fixes #106
> Support repo.repo and repo.owner as template variables

- README.md
- src/action.ts
- tests/__snapshots__/index.test.ts.snap
- tests/index.test.ts
As far as I can see `update_existing=garbage` or `update_existing=false` works as `update_existing=true` today because `Boolean` doesn't parse but casts anything to true/false. With this change `update_existing` can be `true`, `false` and undefined.
- When `true`, an existing issue is updated.
- When `false`, an existing issue is not updated.
- When `undefined`, a new issue is always created.
Closes #108.
> Skip updating an existing issue when update_existing=false.

- README.md
- action.yml
- package-lock.json
- src/action.ts
- tests/__snapshots__/index.test.ts.snap
- tests/index.test.ts
The `search_existing` param lets you specify whether to search open and/or closed existing issues for duplicates (default is `open`).
Closes https://github.com/JasonEtco/create-an-issue/issues/109
> Added search_existing param.

- src/action.ts
- tests/index.test.ts
This PR adds a check for valid search states before attempting to append `is:<state>` to the search query. This should prevent any invalid states (like `all`) from causing it to return no search results.
Closes https://github.com/JasonEtco/create-an-issue/issues/121
> Don't include `is:all` in issue filter

- .github/workflows/ci.yml
- package-lock.json
- src/action.ts
- src/helpers.ts
- tests/__snapshots__/index.test.ts.snap
- tests/fixtures/.github/quotes-in-title.md
- tests/index.test.ts
Without quotes, some queries find more than 100 results, but only the first 100 are returned. This can lead to matching issues titles not being found even when they exist.
Any quotes present in the issue title included in the query will be escaped to avoid conflicting quotes.
> Add quotes around title in search query

- src/helpers.ts
- tests/__snapshots__/index.test.ts.snap
Closes #145 for an unintended regression that is causing a mismatch with the fields that `create-an-issue` is expecting, and fields that GitHub's issue templates support.
> Add more fields to schema
